# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/work/Desktop/JohnPhylo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/work/Desktop/JohnPhylo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/work/Desktop/JohnPhylo/CMakeFiles /Users/work/Desktop/JohnPhylo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/work/Desktop/JohnPhylo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named ncl_shared

# Build rule for target.
ncl_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ncl_shared
.PHONY : ncl_shared

# fast build rule for target.
ncl_shared/fast:
	$(MAKE) $(MAKESILENT) -f lib/ncl/ncl/CMakeFiles/ncl_shared.dir/build.make lib/ncl/ncl/CMakeFiles/ncl_shared.dir/build
.PHONY : ncl_shared/fast

#=============================================================================
# Target rules for targets named ncl_static

# Build rule for target.
ncl_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ncl_static
.PHONY : ncl_static

# fast build rule for target.
ncl_static/fast:
	$(MAKE) $(MAKESILENT) -f lib/ncl/ncl/CMakeFiles/ncl_static.dir/build.make lib/ncl/ncl/CMakeFiles/ncl_static.dir/build
.PHONY : ncl_static/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/Experimental.dir/build.make lib/taskflow/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/Nightly.dir/build.make lib/taskflow/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/Continuous.dir/build.make lib/taskflow/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/NightlyMemoryCheck.dir/build.make lib/taskflow/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/NightlyStart.dir/build.make lib/taskflow/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/NightlyUpdate.dir/build.make lib/taskflow/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/NightlyConfigure.dir/build.make lib/taskflow/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/NightlyBuild.dir/build.make lib/taskflow/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/NightlyTest.dir/build.make lib/taskflow/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/NightlyCoverage.dir/build.make lib/taskflow/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/NightlyMemCheck.dir/build.make lib/taskflow/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/NightlySubmit.dir/build.make lib/taskflow/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/ExperimentalStart.dir/build.make lib/taskflow/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/ExperimentalUpdate.dir/build.make lib/taskflow/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/ExperimentalConfigure.dir/build.make lib/taskflow/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/ExperimentalBuild.dir/build.make lib/taskflow/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/ExperimentalTest.dir/build.make lib/taskflow/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/ExperimentalCoverage.dir/build.make lib/taskflow/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/ExperimentalMemCheck.dir/build.make lib/taskflow/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/ExperimentalSubmit.dir/build.make lib/taskflow/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/ContinuousStart.dir/build.make lib/taskflow/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/ContinuousUpdate.dir/build.make lib/taskflow/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/ContinuousConfigure.dir/build.make lib/taskflow/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/ContinuousBuild.dir/build.make lib/taskflow/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/ContinuousTest.dir/build.make lib/taskflow/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/ContinuousCoverage.dir/build.make lib/taskflow/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/ContinuousMemCheck.dir/build.make lib/taskflow/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f lib/taskflow/CMakeFiles/ContinuousSubmit.dir/build.make lib/taskflow/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

src/core/Alignment.o: src/core/Alignment.cpp.o
.PHONY : src/core/Alignment.o

# target to build an object file
src/core/Alignment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Alignment.cpp.o
.PHONY : src/core/Alignment.cpp.o

src/core/Alignment.i: src/core/Alignment.cpp.i
.PHONY : src/core/Alignment.i

# target to preprocess a source file
src/core/Alignment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Alignment.cpp.i
.PHONY : src/core/Alignment.cpp.i

src/core/Alignment.s: src/core/Alignment.cpp.s
.PHONY : src/core/Alignment.s

# target to generate assembly for a file
src/core/Alignment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Alignment.cpp.s
.PHONY : src/core/Alignment.cpp.s

src/core/EigenSystem.o: src/core/EigenSystem.cpp.o
.PHONY : src/core/EigenSystem.o

# target to build an object file
src/core/EigenSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/EigenSystem.cpp.o
.PHONY : src/core/EigenSystem.cpp.o

src/core/EigenSystem.i: src/core/EigenSystem.cpp.i
.PHONY : src/core/EigenSystem.i

# target to preprocess a source file
src/core/EigenSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/EigenSystem.cpp.i
.PHONY : src/core/EigenSystem.cpp.i

src/core/EigenSystem.s: src/core/EigenSystem.cpp.s
.PHONY : src/core/EigenSystem.s

# target to generate assembly for a file
src/core/EigenSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/EigenSystem.cpp.s
.PHONY : src/core/EigenSystem.cpp.s

src/core/Math.o: src/core/Math.cpp.o
.PHONY : src/core/Math.o

# target to build an object file
src/core/Math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Math.cpp.o
.PHONY : src/core/Math.cpp.o

src/core/Math.i: src/core/Math.cpp.i
.PHONY : src/core/Math.i

# target to preprocess a source file
src/core/Math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Math.cpp.i
.PHONY : src/core/Math.cpp.i

src/core/Math.s: src/core/Math.cpp.s
.PHONY : src/core/Math.s

# target to generate assembly for a file
src/core/Math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Math.cpp.s
.PHONY : src/core/Math.cpp.s

src/core/Msg.o: src/core/Msg.cpp.o
.PHONY : src/core/Msg.o

# target to build an object file
src/core/Msg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Msg.cpp.o
.PHONY : src/core/Msg.cpp.o

src/core/Msg.i: src/core/Msg.cpp.i
.PHONY : src/core/Msg.i

# target to preprocess a source file
src/core/Msg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Msg.cpp.i
.PHONY : src/core/Msg.cpp.i

src/core/Msg.s: src/core/Msg.cpp.s
.PHONY : src/core/Msg.s

# target to generate assembly for a file
src/core/Msg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Msg.cpp.s
.PHONY : src/core/Msg.cpp.s

src/core/Probability.o: src/core/Probability.cpp.o
.PHONY : src/core/Probability.o

# target to build an object file
src/core/Probability.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Probability.cpp.o
.PHONY : src/core/Probability.cpp.o

src/core/Probability.i: src/core/Probability.cpp.i
.PHONY : src/core/Probability.i

# target to preprocess a source file
src/core/Probability.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Probability.cpp.i
.PHONY : src/core/Probability.cpp.i

src/core/Probability.s: src/core/Probability.cpp.s
.PHONY : src/core/Probability.s

# target to generate assembly for a file
src/core/Probability.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Probability.cpp.s
.PHONY : src/core/Probability.cpp.s

src/core/RandomVariable.o: src/core/RandomVariable.cpp.o
.PHONY : src/core/RandomVariable.o

# target to build an object file
src/core/RandomVariable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/RandomVariable.cpp.o
.PHONY : src/core/RandomVariable.cpp.o

src/core/RandomVariable.i: src/core/RandomVariable.cpp.i
.PHONY : src/core/RandomVariable.i

# target to preprocess a source file
src/core/RandomVariable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/RandomVariable.cpp.i
.PHONY : src/core/RandomVariable.cpp.i

src/core/RandomVariable.s: src/core/RandomVariable.cpp.s
.PHONY : src/core/RandomVariable.s

# target to generate assembly for a file
src/core/RandomVariable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/RandomVariable.cpp.s
.PHONY : src/core/RandomVariable.cpp.s

src/core/Settings.o: src/core/Settings.cpp.o
.PHONY : src/core/Settings.o

# target to build an object file
src/core/Settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Settings.cpp.o
.PHONY : src/core/Settings.cpp.o

src/core/Settings.i: src/core/Settings.cpp.i
.PHONY : src/core/Settings.i

# target to preprocess a source file
src/core/Settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Settings.cpp.i
.PHONY : src/core/Settings.cpp.i

src/core/Settings.s: src/core/Settings.cpp.s
.PHONY : src/core/Settings.s

# target to generate assembly for a file
src/core/Settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Settings.cpp.s
.PHONY : src/core/Settings.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/modeling/analysis/Mcmc.o: src/modeling/analysis/Mcmc.cpp.o
.PHONY : src/modeling/analysis/Mcmc.o

# target to build an object file
src/modeling/analysis/Mcmc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/analysis/Mcmc.cpp.o
.PHONY : src/modeling/analysis/Mcmc.cpp.o

src/modeling/analysis/Mcmc.i: src/modeling/analysis/Mcmc.cpp.i
.PHONY : src/modeling/analysis/Mcmc.i

# target to preprocess a source file
src/modeling/analysis/Mcmc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/analysis/Mcmc.cpp.i
.PHONY : src/modeling/analysis/Mcmc.cpp.i

src/modeling/analysis/Mcmc.s: src/modeling/analysis/Mcmc.cpp.s
.PHONY : src/modeling/analysis/Mcmc.s

# target to generate assembly for a file
src/modeling/analysis/Mcmc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/analysis/Mcmc.cpp.s
.PHONY : src/modeling/analysis/Mcmc.cpp.s

src/modeling/model/ConditionalLikelihood.o: src/modeling/model/ConditionalLikelihood.cpp.o
.PHONY : src/modeling/model/ConditionalLikelihood.o

# target to build an object file
src/modeling/model/ConditionalLikelihood.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/model/ConditionalLikelihood.cpp.o
.PHONY : src/modeling/model/ConditionalLikelihood.cpp.o

src/modeling/model/ConditionalLikelihood.i: src/modeling/model/ConditionalLikelihood.cpp.i
.PHONY : src/modeling/model/ConditionalLikelihood.i

# target to preprocess a source file
src/modeling/model/ConditionalLikelihood.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/model/ConditionalLikelihood.cpp.i
.PHONY : src/modeling/model/ConditionalLikelihood.cpp.i

src/modeling/model/ConditionalLikelihood.s: src/modeling/model/ConditionalLikelihood.cpp.s
.PHONY : src/modeling/model/ConditionalLikelihood.s

# target to generate assembly for a file
src/modeling/model/ConditionalLikelihood.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/model/ConditionalLikelihood.cpp.s
.PHONY : src/modeling/model/ConditionalLikelihood.cpp.s

src/modeling/model/Model.o: src/modeling/model/Model.cpp.o
.PHONY : src/modeling/model/Model.o

# target to build an object file
src/modeling/model/Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/model/Model.cpp.o
.PHONY : src/modeling/model/Model.cpp.o

src/modeling/model/Model.i: src/modeling/model/Model.cpp.i
.PHONY : src/modeling/model/Model.i

# target to preprocess a source file
src/modeling/model/Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/model/Model.cpp.i
.PHONY : src/modeling/model/Model.cpp.i

src/modeling/model/Model.s: src/modeling/model/Model.cpp.s
.PHONY : src/modeling/model/Model.s

# target to generate assembly for a file
src/modeling/model/Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/model/Model.cpp.s
.PHONY : src/modeling/model/Model.cpp.s

src/modeling/model/RandomTree.o: src/modeling/model/RandomTree.cpp.o
.PHONY : src/modeling/model/RandomTree.o

# target to build an object file
src/modeling/model/RandomTree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/model/RandomTree.cpp.o
.PHONY : src/modeling/model/RandomTree.cpp.o

src/modeling/model/RandomTree.i: src/modeling/model/RandomTree.cpp.i
.PHONY : src/modeling/model/RandomTree.i

# target to preprocess a source file
src/modeling/model/RandomTree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/model/RandomTree.cpp.i
.PHONY : src/modeling/model/RandomTree.cpp.i

src/modeling/model/RandomTree.s: src/modeling/model/RandomTree.cpp.s
.PHONY : src/modeling/model/RandomTree.s

# target to generate assembly for a file
src/modeling/model/RandomTree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/model/RandomTree.cpp.s
.PHONY : src/modeling/model/RandomTree.cpp.s

src/modeling/model/TransitionProbability.o: src/modeling/model/TransitionProbability.cpp.o
.PHONY : src/modeling/model/TransitionProbability.o

# target to build an object file
src/modeling/model/TransitionProbability.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/model/TransitionProbability.cpp.o
.PHONY : src/modeling/model/TransitionProbability.cpp.o

src/modeling/model/TransitionProbability.i: src/modeling/model/TransitionProbability.cpp.i
.PHONY : src/modeling/model/TransitionProbability.i

# target to preprocess a source file
src/modeling/model/TransitionProbability.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/model/TransitionProbability.cpp.i
.PHONY : src/modeling/model/TransitionProbability.cpp.i

src/modeling/model/TransitionProbability.s: src/modeling/model/TransitionProbability.cpp.s
.PHONY : src/modeling/model/TransitionProbability.s

# target to generate assembly for a file
src/modeling/model/TransitionProbability.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/model/TransitionProbability.cpp.s
.PHONY : src/modeling/model/TransitionProbability.cpp.s

src/modeling/parameters/RateMatrix.o: src/modeling/parameters/RateMatrix.cpp.o
.PHONY : src/modeling/parameters/RateMatrix.o

# target to build an object file
src/modeling/parameters/RateMatrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/parameters/RateMatrix.cpp.o
.PHONY : src/modeling/parameters/RateMatrix.cpp.o

src/modeling/parameters/RateMatrix.i: src/modeling/parameters/RateMatrix.cpp.i
.PHONY : src/modeling/parameters/RateMatrix.i

# target to preprocess a source file
src/modeling/parameters/RateMatrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/parameters/RateMatrix.cpp.i
.PHONY : src/modeling/parameters/RateMatrix.cpp.i

src/modeling/parameters/RateMatrix.s: src/modeling/parameters/RateMatrix.cpp.s
.PHONY : src/modeling/parameters/RateMatrix.s

# target to generate assembly for a file
src/modeling/parameters/RateMatrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/parameters/RateMatrix.cpp.s
.PHONY : src/modeling/parameters/RateMatrix.cpp.s

src/modeling/parameters/trees/Node.o: src/modeling/parameters/trees/Node.cpp.o
.PHONY : src/modeling/parameters/trees/Node.o

# target to build an object file
src/modeling/parameters/trees/Node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/parameters/trees/Node.cpp.o
.PHONY : src/modeling/parameters/trees/Node.cpp.o

src/modeling/parameters/trees/Node.i: src/modeling/parameters/trees/Node.cpp.i
.PHONY : src/modeling/parameters/trees/Node.i

# target to preprocess a source file
src/modeling/parameters/trees/Node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/parameters/trees/Node.cpp.i
.PHONY : src/modeling/parameters/trees/Node.cpp.i

src/modeling/parameters/trees/Node.s: src/modeling/parameters/trees/Node.cpp.s
.PHONY : src/modeling/parameters/trees/Node.s

# target to generate assembly for a file
src/modeling/parameters/trees/Node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/parameters/trees/Node.cpp.s
.PHONY : src/modeling/parameters/trees/Node.cpp.s

src/modeling/parameters/trees/TreeObject.o: src/modeling/parameters/trees/TreeObject.cpp.o
.PHONY : src/modeling/parameters/trees/TreeObject.o

# target to build an object file
src/modeling/parameters/trees/TreeObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/parameters/trees/TreeObject.cpp.o
.PHONY : src/modeling/parameters/trees/TreeObject.cpp.o

src/modeling/parameters/trees/TreeObject.i: src/modeling/parameters/trees/TreeObject.cpp.i
.PHONY : src/modeling/parameters/trees/TreeObject.i

# target to preprocess a source file
src/modeling/parameters/trees/TreeObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/parameters/trees/TreeObject.cpp.i
.PHONY : src/modeling/parameters/trees/TreeObject.cpp.i

src/modeling/parameters/trees/TreeObject.s: src/modeling/parameters/trees/TreeObject.cpp.s
.PHONY : src/modeling/parameters/trees/TreeObject.s

# target to generate assembly for a file
src/modeling/parameters/trees/TreeObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/parameters/trees/TreeObject.cpp.s
.PHONY : src/modeling/parameters/trees/TreeObject.cpp.s

src/modeling/parameters/trees/TreeParameter.o: src/modeling/parameters/trees/TreeParameter.cpp.o
.PHONY : src/modeling/parameters/trees/TreeParameter.o

# target to build an object file
src/modeling/parameters/trees/TreeParameter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/parameters/trees/TreeParameter.cpp.o
.PHONY : src/modeling/parameters/trees/TreeParameter.cpp.o

src/modeling/parameters/trees/TreeParameter.i: src/modeling/parameters/trees/TreeParameter.cpp.i
.PHONY : src/modeling/parameters/trees/TreeParameter.i

# target to preprocess a source file
src/modeling/parameters/trees/TreeParameter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/parameters/trees/TreeParameter.cpp.i
.PHONY : src/modeling/parameters/trees/TreeParameter.cpp.i

src/modeling/parameters/trees/TreeParameter.s: src/modeling/parameters/trees/TreeParameter.cpp.s
.PHONY : src/modeling/parameters/trees/TreeParameter.s

# target to generate assembly for a file
src/modeling/parameters/trees/TreeParameter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/modeling/parameters/trees/TreeParameter.cpp.s
.PHONY : src/modeling/parameters/trees/TreeParameter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... main"
	@echo "... ncl_shared"
	@echo "... ncl_static"
	@echo "... src/core/Alignment.o"
	@echo "... src/core/Alignment.i"
	@echo "... src/core/Alignment.s"
	@echo "... src/core/EigenSystem.o"
	@echo "... src/core/EigenSystem.i"
	@echo "... src/core/EigenSystem.s"
	@echo "... src/core/Math.o"
	@echo "... src/core/Math.i"
	@echo "... src/core/Math.s"
	@echo "... src/core/Msg.o"
	@echo "... src/core/Msg.i"
	@echo "... src/core/Msg.s"
	@echo "... src/core/Probability.o"
	@echo "... src/core/Probability.i"
	@echo "... src/core/Probability.s"
	@echo "... src/core/RandomVariable.o"
	@echo "... src/core/RandomVariable.i"
	@echo "... src/core/RandomVariable.s"
	@echo "... src/core/Settings.o"
	@echo "... src/core/Settings.i"
	@echo "... src/core/Settings.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/modeling/analysis/Mcmc.o"
	@echo "... src/modeling/analysis/Mcmc.i"
	@echo "... src/modeling/analysis/Mcmc.s"
	@echo "... src/modeling/model/ConditionalLikelihood.o"
	@echo "... src/modeling/model/ConditionalLikelihood.i"
	@echo "... src/modeling/model/ConditionalLikelihood.s"
	@echo "... src/modeling/model/Model.o"
	@echo "... src/modeling/model/Model.i"
	@echo "... src/modeling/model/Model.s"
	@echo "... src/modeling/model/RandomTree.o"
	@echo "... src/modeling/model/RandomTree.i"
	@echo "... src/modeling/model/RandomTree.s"
	@echo "... src/modeling/model/TransitionProbability.o"
	@echo "... src/modeling/model/TransitionProbability.i"
	@echo "... src/modeling/model/TransitionProbability.s"
	@echo "... src/modeling/parameters/RateMatrix.o"
	@echo "... src/modeling/parameters/RateMatrix.i"
	@echo "... src/modeling/parameters/RateMatrix.s"
	@echo "... src/modeling/parameters/trees/Node.o"
	@echo "... src/modeling/parameters/trees/Node.i"
	@echo "... src/modeling/parameters/trees/Node.s"
	@echo "... src/modeling/parameters/trees/TreeObject.o"
	@echo "... src/modeling/parameters/trees/TreeObject.i"
	@echo "... src/modeling/parameters/trees/TreeObject.s"
	@echo "... src/modeling/parameters/trees/TreeParameter.o"
	@echo "... src/modeling/parameters/trees/TreeParameter.i"
	@echo "... src/modeling/parameters/trees/TreeParameter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

